type Copy = { es: string; en: string };
type StoryImage = { file: string; width: number; height: number; alt: Copy };
type StorySection = {
  layout: "split" | "reverse" | "wide-top" | "phones" | "phones-reverse";
  label: Copy;
  title: Copy;
  paragraphs: Copy[];
  images: StoryImage[];
};
type Story = { headline: Copy; introduction: Copy; sections: StorySection[]; closingTitle: Copy; closing: Copy };
const copy = (es: string, en: string): Copy => ({ es, en });
const desktop = (file: string, es: string, en: string): StoryImage => ({ file, width: file === "mind2" ? 2871 : 2880, height: 1800, alt: copy(es, en) });
const phone = (file: string, es: string, en: string): StoryImage => ({ file, width: ({ mobi2: 1236, mobi4: 1241, mobi6: 1241, mobi7: 1245 } as Record<string, number>)[file] ?? 1242, height: 2688, alt: copy(es, en) });

export const projectStories = {
  ecohabit: {
    headline: copy("Un agente conectado al trabajo de cada vendedor.", "An agent connected to each salesperson’s work."),
    introduction: copy("Junto a Mindpraxis, desarrollé Ecohabit como **una plataforma construida alrededor de un agente de IA**. Conecté la conversación con la agenda, el conocimiento interno, las métricas y las herramientas de gestión para acompañar el trabajo y el aprendizaje del equipo de ventas.", "Together with Mindpraxis, I developed Ecohabit as **a platform built around an AI agent**. I connected conversation to the agenda, internal knowledge, metrics and management tools to support the sales team’s work and learning."),
    sections: [
      {
        layout: "split", label: copy("El agente en el día a día", "The agent in everyday work"), title: copy("Un agente que conoce el contexto de trabajo.", "An agent with work context."),
        paragraphs: [copy("Construí el inicio de Ecohabit alrededor de **un agente conectado a la agenda, los objetivos y las métricas del vendedor**. Ante una pregunta como «¿qué tengo pendiente hoy?», puede consultar las actividades registradas y distinguir lo pendiente de lo completado.", "I built Ecohabit’s home around **an agent connected to the salesperson’s agenda, goals and metrics**. When asked something like ‘What is still on my list today?’, it can retrieve recorded activities and distinguish pending work from completed tasks."), copy("Diseñé la conversación y las vistas de seguimiento como partes de un mismo sistema. El vendedor puede consultar su información en lenguaje natural y continuar en la actividad correspondiente; el agente trabaja con el contexto de su usuario y su empresa.", "I designed conversation and progress views as parts of the same system. Salespeople can ask about their information in natural language and continue into the relevant activity. The agent works within their user and company context.")],
        images: [desktop("mind2", "Inicio de Ecohabit con objetivos, tareas y evolución semanal", "Ecohabit home with goals, tasks and weekly progress")],
      },
      {
        layout: "wide-top", label: copy("De la consulta al reporte", "From a question to a report"), title: copy("Herramientas que convierten una conversación en trabajo útil.", "Tools that turn conversation into useful work."),
        paragraphs: [copy("Desarrollé la lógica que permite al agente **seleccionar herramientas, consultar información y encadenar sus resultados**. Para analizar productividad puede recuperar métricas de un período y usarlas en un informe que el usuario puede revisar y editar, como el que se ve en esta pantalla.", "I developed the logic that lets the agent **select tools, retrieve information and use their results across multiple steps**. To analyse productivity, it can retrieve metrics for a period and use them in a report the user can review and edit, like the one shown here."), copy("También conecté una **base de conocimiento interna** para recuperar material relevante de la empresa. La conversación conserva historial y contexto, y muestra los pasos de consulta mientras se genera la respuesta. El agente tiene instrucciones para reconocer cuando el material disponible no alcanza para responder.", "I also connected an **internal knowledge base** to retrieve relevant company material. The conversation retains history and context, and shows retrieval steps as the response is generated. The agent is instructed to acknowledge when the available material is insufficient to answer.")],
        images: [desktop("mind3", "Asistente de Ecohabit generando un reporte de productividad", "Ecohabit assistant generating a productivity report")],
      },
      {
        layout: "reverse", label: copy("Agenda conectada al agente", "An agenda connected to the agent"), title: copy("Los hábitos forman parte del contexto.", "Habits are part of the context."),
        paragraphs: [copy("Integré **rutinas, hábitos, evaluaciones, fichas y objetivos** con las herramientas de consulta del agente. Puede recuperar la agenda de hoy, mañana o un período concreto, leer el estado de cada actividad y devolver accesos a las tareas correspondientes.", "I integrated **routines, habits, assessments, coaching forms and goals** with the agent’s retrieval tools. It can retrieve the agenda for today, tomorrow or a specific period, read each activity’s status and return links to the relevant tasks."), copy("La agenda y el chat consultan los mismos registros. Así, el acompañamiento del agente se apoya en lo que la persona tiene asignado y en su avance registrado, no en una lista de tareas inventada durante la conversación.", "The agenda and chat use the same records. The agent’s support is grounded in the person’s assignments and recorded progress, rather than a task list invented during the conversation.")],
        images: [desktop("mind4", "Agenda de Ecohabit con tareas, hábitos y eventos por fecha", "Ecohabit agenda showing tasks, habits and events by date")],
      },
      {
        layout: "split", label: copy("Una interfaz para trabajar con el agente", "A workspace for the agent"), title: copy("La conversación dentro de una herramienta cotidiana.", "Conversation inside an everyday workspace."),
        paragraphs: [copy("Diseñé el espacio donde el equipo interactúa con el agente y consulta sus resultados. Incorporé **preferencias de color y visualización** para que cada persona pueda adaptar la interfaz, manteniendo el acceso a sus conversaciones, actividades y métricas en un mismo entorno.", "I designed the workspace where the team interacts with the agent and reviews its results. I added **colour and display preferences** so each person can adapt the interface while keeping conversations, activities and metrics in the same environment.")],
        images: [desktop("mind5", "Opciones de personalización de colores en Ecohabit", "Ecohabit color customization options")],
      },
      {
        layout: "wide-top", label: copy("Gestión con confirmación", "Management with confirmation"), title: copy("Un agente que puede actuar, con un alcance definido.", "An agent that can act within a defined scope."),
        paragraphs: [copy("Desarrollé herramientas para que el agente pueda **crear, consultar y modificar recursos de la empresa**: usuarios, roles, sucursales, objetivos, rutinas y evaluaciones. Las acciones de escritura incluyen una vista previa y un paso de confirmación para que el equipo revise qué se va a cambiar.", "I developed tools that let the agent **create, retrieve and modify company resources**: users, roles, branches, goals, routines and assessments. Write actions include a preview and a confirmation step so the team can review what will change."), copy("Las herramientas de gestión se filtran según los permisos del usuario y vuelven a comprobarlos al ejecutar la operación. Definí qué acciones están disponibles desde la conversación y cuáles deben resolverse en el panel. El agente no tiene acceso irrestricto al sistema.", "Management tools are filtered by user permissions and check those permissions again when executing an operation. I defined which actions are available through conversation and which must be handled in the dashboard. The agent does not have unrestricted system access.")],
        images: [desktop("mind6", "Entorno de gestión de Ecohabit y herramientas de administración", "Ecohabit management workspace and administration tools")],
      },
      {
        layout: "reverse", label: copy("Métricas al alcance del agente", "Metrics available to the agent"), title: copy("Analizar con datos del negocio.", "Analyse with business data."),
        paragraphs: [copy("Conecté el agente con **facturación, tickets, unidades, productividad y avance de objetivos**. Sus herramientas permiten consultar rangos de fechas y recuperar los indicadores necesarios para una pregunta concreta, en lugar de depender de que el usuario copie los datos al chat.", "I connected the agent to **revenue, tickets, units, productivity and goal progress**. Its tools can query date ranges and retrieve the indicators needed for a specific question, without requiring users to copy the data into chat."), copy("El vendedor puede consultar sus propios resultados. Las consultas sobre otras personas, sucursales o el conjunto de la empresa requieren permiso de métricas. Construí también las vistas de detalle para que el equipo pueda contrastar el análisis del agente con los registros del sistema.", "Salespeople can query their own results. Queries about other people, branches or the company as a whole require metrics permissions. I also built detailed views so the team can check the agent’s analysis against system records.")],
        images: [desktop("mind7", "Tabla de métricas comerciales y objetivos de Ecohabit", "Ecohabit commercial metrics and goals table")],
      },
      {
        layout: "wide-top", label: copy("Un agente para aprender", "An agent for learning"), title: copy("Conocimiento de la empresa, llevado a la práctica.", "Company knowledge, put into practice."),
        paragraphs: [copy("Incorporé un **modo tutor** en el que el agente recupera material de la base de conocimiento, explica un tema y prepara preguntas de práctica. El usuario responde desde la conversación y recibe una devolución sobre sus respuestas.", "I added a **tutor mode** in which the agent retrieves knowledge-base material, explains a topic and prepares practice questions. Users answer within the conversation and receive feedback on their responses."), copy("Conecté ese acompañamiento con las fichas y evaluaciones de la plataforma. El equipo puede revisar respuestas y evolución del aprendizaje junto a hábitos y resultados comerciales, con el agente como apoyo para la capacitación y el seguimiento.", "I connected that support to the platform’s coaching forms and assessments. The team can review responses and learning progress alongside habits and commercial results, with the agent supporting training and follow-up.")],
        images: [desktop("mind8", "Comparación de respuestas y evaluaciones de vendedores en Ecohabit", "Comparison of salesperson responses and assessments in Ecohabit")],
      },
    ],
    closingTitle: copy("Un agente integrado, no un chat aislado.", "An integrated agent, not a standalone chat."),
    closing: copy("Construí el agente, sus herramientas y el entorno operativo con **Next.js y TypeScript**. Conecté conocimiento interno, datos comerciales y acciones de gestión con permisos, confirmaciones y vistas para revisar resultados. La plataforma hace que la conversación sea una forma de trabajar sobre información y procesos reales.", "I built the agent, its tools and its operational workspace with **Next.js and TypeScript**. I connected internal knowledge, commercial data and management actions with permissions, confirmations and views for reviewing results. The platform makes conversation a way to work with real information and processes."),
  },
  izr: {
    headline: copy("Un agente de voz que convierte llamadas en consultas para el equipo.", "A voice agent that turns calls into enquiries for the team."),
    introduction: copy("Diseñé y desarrollé para Izrastzoff **un agente de voz integrado a la telefonía y al seguimiento comercial**. Su trabajo es atender fuera de horario, clasificar la consulta y reunir datos para que un asesor humano continúe la gestión. Construí también las herramientas de registro, distribución y supervisión de ese flujo.", "I designed and developed for Izrastzoff **a voice agent integrated with telephony and commercial follow-up**. Its role is to answer after hours, classify enquiries and gather information for a human adviser to continue. I also built the tools to record, route and oversee that workflow."),
    sections: [
      {
        layout: "wide-top", label: copy("Un agente con una tarea definida", "An agent with a defined role"), title: copy("Atender, clasificar y preparar la consulta.", "Answer, classify and prepare the enquiry."),
        paragraphs: [copy("Definí el flujo de conversación del agente para distinguir **búsquedas de propiedades, pedidos de tasación y otras consultas**. A partir de esa clasificación reúne los datos pertinentes: por ejemplo, zona y presupuesto para una búsqueda, o dirección y características de la propiedad para una tasación.", "I defined the agent’s conversation flow to distinguish **property searches, valuation requests and other enquiries**. That classification guides the information it gathers: for example, area and budget for a search, or the address and property details for a valuation."), copy("El alcance es recibir y preparar la consulta para un asesor, no reemplazar su criterio ni realizar una tasación durante la llamada. Construí un panel con el estado del agente, las llamadas y la actividad reciente para que el equipo pueda supervisar esa atención.", "Its scope is to receive and prepare the enquiry for an adviser, not replace their judgement or value a property during the call. I built a dashboard with agent status, calls and recent activity so the team can oversee that service.")],
        images: [desktop("izr1", "Panel de Izrastzoff con estado del agente y actividad de llamadas", "Izrastzoff dashboard with agent status and call activity")],
      },
      {
        layout: "reverse", label: copy("Visibilidad de la operación", "Operational visibility"), title: copy("Medir lo que hace el agente.", "Measure what the agent does."),
        paragraphs: [copy("Instrumenté la operación para registrar **cantidad de llamadas, duración, consumo de IA y costo estimado**. El panel permite observar el uso del agente y relacionarlo con las consultas recibidas, sin depender únicamente de una demostración de voz.", "I instrumented operations to record **call volume, duration, AI usage and estimated cost**. The dashboard makes the agent’s usage visible alongside incoming enquiries, beyond a voice demonstration."), copy("Los eventos de actividad complementan las métricas: permiten revisar qué ocurrió en una llamada y detectar errores del servicio. Construí estas vistas como parte del sistema que necesita el equipo para operar el agente.", "Activity events complement the metrics: they help the team review what happened during a call and identify service errors. I built these views as part of the system the team needs to operate the agent.")],
        images: [desktop("izr2", "Métricas de llamadas, duración y gasto de IA de Izrastzoff", "Izrastzoff call, duration and AI cost metrics")],
      },
      {
        layout: "split", label: copy("De la conversación al registro", "From conversation to a record"), title: copy("El agente deja información lista para continuar.", "The agent leaves information ready for follow-up."),
        paragraphs: [copy("Integré herramientas para que el agente **guarde los datos a medida que conversa y consolide la ficha al finalizar**. Contacto, motivo, resumen y requisitos quedan en registros estructurados, separados según se trate de una búsqueda, una tasación u otra consulta.", "I integrated tools that let the agent **save information during the conversation and consolidate the record when it ends**. Contact details, purpose, summary and requirements become structured records, organised by property search, valuation or other enquiry."), copy("El asesor recibe contexto para retomar la gestión. También contemplé llamadas interrumpidas: el sistema puede conservar la información reunida hasta ese momento. El valor del agente está tanto en conversar como en dejar un registro útil para el equipo.", "The adviser receives context to continue the enquiry. I also accounted for interrupted calls: the system can retain information gathered up to that point. The agent’s value lies both in conversation and in leaving a useful record for the team.")],
        images: [desktop("izr3", "Listado de prospectos y motivos de consulta de Izrastzoff", "Izrastzoff prospects and enquiry categories")],
      },
      {
        layout: "wide-top", label: copy("Entrega al equipo humano", "Handoff to the human team"), title: copy("Una consulta atendida tiene que llegar a quien la sigue.", "An answered enquiry must reach the person following up."),
        paragraphs: [copy("Conecté la ficha del agente con **notificaciones por correo según el tipo de consulta**. El equipo configura qué destinatarios reciben búsquedas, tasaciones u otros temas. Así, la conversación desemboca en un paso concreto de seguimiento humano.", "I connected the agent’s record to **email notifications routed by enquiry type**. The team configures which recipients receive searches, valuations or other topics. The conversation leads to a concrete human follow-up step."), copy("Separé el guardado de la ficha del envío del correo y contemplé el control de duplicados. Si falla una notificación, la consulta permanece registrada y el error queda visible para poder revisar la entrega.", "I separated record storage from email delivery and accounted for duplicate notifications. If a notification fails, the enquiry remains recorded and the error is logged so delivery can be reviewed.")],
        images: [desktop("izr4", "Configuración de destinatarios de correos según consulta inmobiliaria", "Email recipient settings by real estate enquiry type")],
      },
      {
        layout: "reverse", label: copy("Control del agente de voz", "Voice agent controls"), title: copy("Integrado a la telefonía, controlado por el equipo.", "Integrated with telephony, controlled by the team."),
        paragraphs: [copy("Integré **telefonía SIP/Asterisk, audio en tiempo real y herramientas de registro**. El agente escucha y responde durante la llamada, con manejo de interrupciones para acompañar una conversación en lugar de limitarse a reproducir mensajes grabados.", "I integrated **SIP/Asterisk telephony, real-time audio and record-saving tools**. The agent listens and responds during calls, handling interruptions to support conversation rather than simply playing recorded messages."), copy("El panel permite activar o desactivar la atención y elegir o probar la voz. Esos controles, junto con el historial y los eventos, forman parte de la operación del agente: el equipo conserva visibilidad y control sobre el servicio.", "The dashboard lets the team enable or disable answering and choose or preview the voice. Those controls, alongside history and activity events, are part of operating the agent: the team retains visibility and control over the service.")],
        images: [desktop("izr5", "Configuración y prueba de voz del agente de Izrastzoff", "Izrastzoff agent voice settings and preview")],
      },
    ],
    closingTitle: copy("No solo una voz: un circuito completo de atención.", "More than a voice: a complete enquiry workflow."),
    closing: copy("Conecté **telefonía SIP/Asterisk, una IA de voz en tiempo real, PostgreSQL y correo electrónico** con un panel web. Cada parte cumple una función: conversar, conservar la consulta, entregarla al equipo y hacer visible la operación. El resultado es un flujo que continúa después de colgar.", "I connected **SIP/Asterisk telephony, real-time voice AI, PostgreSQL and email** with a web dashboard. Each part has a purpose: converse, preserve the enquiry, deliver it to the team and make operations visible. The workflow continues after the caller hangs up."),
  },
  "mobihunter-admin": {
    headline: copy("IA integrada al contenido y a la operación.", "AI integrated into content and operations."),
    introduction: copy("Desarrollé para Mobihunter **un flujo de gestión con traducción de contenido mediante IA**, conectado a la app y a los datos del negocio. El equipo prepara juegos, preguntas y desafíos, revisa las traducciones y conserva el control de lo que guarda y publica. Es un caso de integración de IA en un proceso concreto de trabajo.", "I developed for Mobihunter **a management workflow with AI-powered content translation**, connected to the app and business data. The team prepares games, questions and challenges, reviews translations and retains control over what it saves and publishes. It is a case of integrating AI into a specific operational process."),
    sections: [
      {
        layout: "split", label: copy("IA dentro del flujo de gestión", "AI inside the management workflow"), title: copy("Una integración que acompaña el trabajo del equipo.", "An integration that supports the team’s work."),
        paragraphs: [copy("Construí el panel donde el equipo administra **juegos, preguntas, desafíos, usuarios y eventos**, e integré la traducción con IA en los formularios de contenido. La IA se utiliza dentro del proceso de edición, sin obligar al equipo a copiar textos entre herramientas externas.", "I built the dashboard where the team manages **games, questions, challenges, users and events**, and integrated AI translation into content forms. AI is used within the editing process, without requiring the team to copy text between external tools."), copy("El contenido guardado alimenta la app, y las compras y partidas vuelven al panel como datos operativos. Conecté esas piezas para que la IA tenga un lugar definido en el trabajo y sus resultados formen parte del sistema que el equipo ya usa.", "Saved content feeds the app, while purchases and game sessions return to the dashboard as operational data. I connected those parts so AI has a defined role in the workflow and its output belongs to the system the team uses.")],
        images: [desktop("mobiadmin1", "Inicio del panel de administración de Mobihunter", "Mobihunter administration home")],
      },
      {
        layout: "wide-top", label: copy("Datos para operar y mejorar", "Data for operations and improvement"), title: copy("El contenido publicado tiene un recorrido medible.", "Published content has a measurable journey."),
        paragraphs: [copy("Conecté la experiencia del jugador con **métricas de participación, tiempos, respuestas y ayudas utilizadas**. Los gráficos resumen la actividad y el detalle de partidas permite revisar qué ocurrió en cada experiencia.", "I connected the player experience to **metrics for participation, timing, answers and hints used**. Charts summarise activity, while session details let the team review what happened in each experience."), copy("Los filtros por juego y período permiten acotar la revisión. La generación de traducciones es una parte del proceso; estas vistas muestran cómo se utiliza después el contenido que el equipo publica.", "Game and period filters narrow the review. Translation generation is one part of the process; these views show how the content published by the team is used afterwards.")],
        images: [desktop("mobiadmin2", "Métricas de participación y partidas de Mobihunter", "Mobihunter participation and game-session metrics")],
      },
      {
        layout: "reverse", label: copy("Integración con el negocio", "Business integration"), title: copy("Compras y gestión conectadas.", "Purchases and management, connected."),
        paragraphs: [copy("Integré los registros de compra con **una vista de ingresos y detalle de operaciones**. El equipo puede filtrar movimientos y relacionarlos con las experiencias del catálogo, trabajando sobre datos registrados por el sistema.", "I integrated purchase records with **a revenue view and transaction details**. The team can filter transactions and relate them to catalogue experiences, working with data recorded by the system."), copy("El panel conecta preparación de contenido, publicación, participación e ingresos. Ese entorno operativo acompaña la integración de IA: el resultado de una traducción termina dentro de una experiencia que se puede gestionar y medir.", "The dashboard connects content preparation, publishing, participation and revenue. That operational environment supports the AI integration: a translation becomes part of an experience that can be managed and measured.")],
        images: [desktop("mobiadmin3", "Panel de ganancias y compras de Mobihunter", "Mobihunter revenue and purchases dashboard")],
      },
      {
        layout: "split", label: copy("Trazabilidad del recorrido", "Journey tracking"), title: copy("También registrar lo que queda sin completar.", "Track what remains incomplete too."),
        paragraphs: [copy("Desarrollé el seguimiento de **compras que no terminaron en una partida completada**. El equipo puede distinguir una transacción de una experiencia finalizada y detectar casos que necesitan revisión.", "I developed tracking for **purchases that did not lead to a completed session**. The team can distinguish a transaction from a finished experience and identify cases that need review."), copy("Esta vista aporta contexto para mejorar el proceso. Los registros indican dónde investigar, pero no explican por sí solos por qué alguien abandonó: esa interpretación sigue requiriendo revisión del equipo y, cuando corresponde, conversación con el usuario.", "This view provides context for improving the process. Records show where to investigate, but do not explain why someone dropped out on their own. That interpretation still requires the team’s review and, when appropriate, a conversation with the user.")],
        images: [desktop("mobiadmin4", "Seguimiento de abandono y partidas sin completar en Mobihunter", "Mobihunter drop-off and incomplete-session tracking")],
      },
      {
        layout: "wide-top", label: copy("Traducción de contenido con IA", "AI-powered content translation"), title: copy("Preparar contenido en varios idiomas desde el panel.", "Prepare multilingual content from the dashboard."),
        paragraphs: [copy("Integré una **automatización de traducción con IA** para juegos, preguntas y desafíos en español, inglés y portugués. El equipo parte del contenido original y genera las versiones en los otros idiomas desde el editor, donde puede revisarlas antes de guardar.", "I integrated **AI-powered translation automation** for games, questions and challenges in Spanish, English and Portuguese. The team starts with the original content and generates the other language versions from the editor, where it can review them before saving."), copy("Desarrollé el procesamiento por bloques, la validación de las respuestas y los reintentos ante fallos. También separé las imágenes y los videos del texto enviado al modelo para volver a insertarlos en las traducciones, manteniendo el contenido multimedia fuera de la generación.", "I developed batch processing, response validation and retries on failure. I also separated images and videos from the text sent to the model and reinserted them into the translations, keeping media outside the generation process.")],
        images: [desktop("mobiadmin5", "Catálogo de juegos con edición y activación en Mobihunter", "Mobihunter game catalogue with editing and activation")],
      },
      {
        layout: "reverse", label: copy("Reglas y control humano", "Rules and human control"), title: copy("La IA prepara traducciones. El equipo define la experiencia.", "AI prepares translations. The team defines the experience."),
        paragraphs: [copy("Construí la edición de preguntas, desafíos y **respuestas admitidas** junto al flujo de traducción. El equipo conserva la definición de las consignas y las reglas que encontrará el jugador; generar una traducción no equivale a publicarla automáticamente.", "I built editing for questions, challenges and **accepted answers** alongside the translation workflow. The team retains control over challenges and the rules players encounter. Generating a translation does not automatically publish it."), copy("La integración tiene un alcance concreto: asistir en la preparación multilingüe del contenido. Las decisiones de edición, guardado y activación permanecen en el panel, con una separación clara entre el resultado de la IA y las acciones del equipo.", "The integration has a specific scope: helping prepare multilingual content. Editing, saving and activation decisions remain in the dashboard, with a clear separation between AI output and the team’s actions.")],
        images: [desktop("mobiadmin6", "Gestión de preguntas y respuestas aceptadas de Mobihunter", "Mobihunter question and accepted-answer management")],
      },
    ],
    closingTitle: copy("IA con un propósito y un lugar en la operación.", "AI with a purpose and a place in operations."),
    closing: copy("Desarrollé el panel con **Next.js, TypeScript y Firebase** e integré la traducción con IA en el flujo de contenido. El alcance de este caso es automatización asistida e integración de sistemas, con revisión humana y datos para seguir la operación.", "I developed the dashboard with **Next.js, TypeScript and Firebase** and integrated AI translation into the content workflow. This case covers assisted automation and systems integration, with human review and data to monitor operations."),
  },
  "mobihunter-app": {
    headline: copy("Del contenido traducido con IA a la experiencia del jugador.", "From AI-translated content to the player experience."),
    introduction: copy("Desarrollé la app de Mobihunter como **la experiencia móvil conectada al panel y al contenido traducido con IA**. Integré catálogo, acceso, preguntas, desafíos, progreso y resultados para que el trabajo realizado por el equipo llegue al jugador y vuelva al negocio como información de uso.", "I developed the Mobihunter app as **the mobile experience connected to the dashboard and AI-translated content**. I integrated the catalogue, access, questions, challenges, progress and results so the team’s work reaches players and returns to the business as usage information."),
    sections: [
      {
        layout: "phones", label: copy("Del contenido con IA a la app", "From AI-assisted content to the app"), title: copy("La integración llega hasta el jugador.", "The integration reaches the player."),
        paragraphs: [copy("Conecté el catálogo y la ficha de cada juego con **el contenido que el equipo prepara, traduce con IA y guarda en el panel**. La app presenta ubicación, duración, descripción e instrucciones en el idioma elegido por el usuario.", "I connected the catalogue and game details to **the content the team prepares, translates with AI and saves in the dashboard**. The app presents location, duration, descriptions and instructions in the user’s chosen language."), copy("La IA participa en la preparación del contenido; la app utiliza las versiones guardadas. El jugador puede elegir una experiencia y acceder a ella sin esperar una nueva generación de texto durante ese recorrido.", "AI is involved in content preparation; the app uses the saved versions. Players can choose and access an experience without waiting for new text generation during that journey.")],
        images: [phone("mobi2", "Tarjetas de experiencias y juegos de Mobihunter", "Mobihunter experience and game cards"), phone("mobi3", "Ficha de un juego de Mobihunter con descripción e instrucciones", "Mobihunter game details with description and instructions")],
      },
      {
        layout: "phones-reverse", label: copy("Acceso conectado", "Connected access"), title: copy("Del contenido publicado al acceso compartido.", "From published content to shared access."),
        paragraphs: [copy("Integré **códigos QR y enlaces compartidos** para abrir una experiencia desde otro celular. El acceso apunta al mismo juego y al contenido gestionado por el equipo, manteniendo conectadas la publicación y la participación.", "I integrated **QR codes and shared links** to open an experience from another phone. Access points to the same game and team-managed content, keeping publishing and participation connected."), copy("Esta parte resuelve la distribución de la experiencia: una vez preparado el contenido, el equipo puede hacerlo llegar al jugador sin pedirle que lo busque manualmente en el catálogo.", "This part handles experience distribution: once the content is ready, the team can get it to players without asking them to find it manually in the catalogue.")],
        images: [phone("mobi4", "Código QR y opciones para compartir un juego de Mobihunter", "QR code and sharing options for a Mobihunter game")],
      },
      {
        layout: "phones", label: copy("Una experiencia integrada", "An integrated experience"), title: copy("El sistema detrás del contenido.", "The system behind the content."),
        paragraphs: [copy("Construí una navegación que reúne **búsqueda, categorías y juegos disponibles**, conectada al catálogo del panel. La app presenta las experiencias activadas por el equipo y permite pasar de la exploración al juego dentro del mismo entorno.", "I built navigation bringing together **search, categories and available games**, connected to the dashboard’s catalogue. The app presents experiences activated by the team and lets players move from discovery to gameplay in the same environment."), copy("La integración de IA necesita también una interfaz donde su resultado pueda usarse. En este caso, conecté las versiones del contenido con las pantallas del jugador, sin convertir la partida en una conversación con un agente.", "An AI integration also needs an interface where its output can be used. In this case, I connected content versions to player screens, without turning gameplay into a conversation with an agent.")],
        images: [phone("mobi5", "Inicio de Mobihunter con búsqueda, categorías y navegación inferior", "Mobihunter home with search, categories and bottom navigation")],
      },
      {
        layout: "phones-reverse", label: copy("Resultados que vuelven al negocio", "Results that feed back into the business"), title: copy("De la participación a los datos operativos.", "From participation to operational data."),
        paragraphs: [copy("Conecté el cierre de la partida con **tiempo, respuestas correctas, errores, ayudas y ranking**. El jugador puede revisar su desempeño y valorar la experiencia; el equipo recibe los registros que alimentan sus métricas de operación.", "I connected the end of each session to **time, correct answers, mistakes, hints and rankings**. Players can review their performance and rate the experience, while the team receives the records that feed its operational metrics."), copy("El recorrido conecta el contenido preparado con IA, su uso en la app y la información que vuelve al panel. Es la parte de integración que hace que una automatización sea útil dentro de un producto y un proceso de negocio.", "The journey connects AI-assisted content preparation, its use in the app and information returning to the dashboard. This integration makes an automation useful within a product and a business process.")],
        images: [phone("mobi6", "Resumen de partida con tiempo, respuestas y ayudas de Mobihunter", "Mobihunter session summary with time, answers and hints"), phone("mobi7", "Ranking de jugadores y valoración de una experiencia de Mobihunter", "Mobihunter player ranking and experience rating")],
      },
    ],
    closingTitle: copy("Una integración de punta a punta.", "An end-to-end integration."),
    closing: copy("Construí la experiencia móvil con **Next.js, TypeScript y Firebase**, conectada a la gestión de contenido y la traducción con IA. El caso reúne interfaces, datos e integración operativa; la IA asiste en el contenido y la app resuelve la participación del jugador.", "I built the mobile experience with **Next.js, TypeScript and Firebase**, connected to content management and AI translation. This case brings together interfaces, data and operational integration: AI assists with content, while the app handles the player experience."),
  },
} satisfies Record<string, Story>;

export type ProjectStoryKey = keyof typeof projectStories;
